# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SDL <- function(x, Sigma) {
    .Call('Rnmr1D_SDL', PACKAGE = 'Rnmr1D', x, Sigma)
}

C_write_pack <- function(x, pmin, pmax, ff) {
    invisible(.Call('Rnmr1D_C_write_pack', PACKAGE = 'Rnmr1D', x, pmin, pmax, ff))
}

C_read_pack <- function(ff) {
    .Call('Rnmr1D_C_read_pack', PACKAGE = 'Rnmr1D', ff)
}

C_findPeaks <- function(x, y, sig, DW, minRatio, minInt0, minInt, bPlasma) {
    .Call('Rnmr1D_C_findPeaks', PACKAGE = 'Rnmr1D', x, y, sig, DW, minRatio, minInt0, minInt, bPlasma)
}

C_corr_spec_re <- function(l) {
    .Call('Rnmr1D_C_corr_spec_re', PACKAGE = 'Rnmr1D', l)
}

C_corr_spec_im <- function(l) {
    .Call('Rnmr1D_C_corr_spec_im', PACKAGE = 'Rnmr1D', l)
}

C_phc0_fn <- function(l, phc0) {
    .Call('Rnmr1D_C_phc0_fn', PACKAGE = 'Rnmr1D', l, phc0)
}

C_phc1_fn <- function(l, phc1) {
    .Call('Rnmr1D_C_phc1_fn', PACKAGE = 'Rnmr1D', l, phc1)
}

C_optim_phc <- function(s, p, fn) {
    .Call('Rnmr1D_C_optim_phc', PACKAGE = 'Rnmr1D', s, p, fn)
}

lowpass1 <- function(x, alpha) {
    .Call('Rnmr1D_lowpass1', PACKAGE = 'Rnmr1D', x, alpha)
}

WinMoy <- function(v, n1, n2) {
    .Call('Rnmr1D_WinMoy', PACKAGE = 'Rnmr1D', v, n1, n2)
}

Smooth <- function(v, n) {
    .Call('Rnmr1D_Smooth', PACKAGE = 'Rnmr1D', v, n)
}

Ajust_LB <- function(s, b, n1, n2) {
    invisible(.Call('Rnmr1D_Ajust_LB', PACKAGE = 'Rnmr1D', s, b, n1, n2))
}

C_Estime_LB <- function(l, s, istart, iend) {
    .Call('Rnmr1D_C_Estime_LB', PACKAGE = 'Rnmr1D', l, s, istart, iend)
}

spec_ref_interval <- function(x, istart, iend) {
    .Call('Rnmr1D_spec_ref_interval', PACKAGE = 'Rnmr1D', x, istart, iend)
}

C_spec_ref <- function(x) {
    .Call('Rnmr1D_C_spec_ref', PACKAGE = 'Rnmr1D', x)
}

C_MedianSpec <- function(x) {
    .Call('Rnmr1D_C_MedianSpec', PACKAGE = 'Rnmr1D', x)
}

C_segment_shifts <- function(x, istart, iend, decal_max) {
    .Call('Rnmr1D_C_segment_shifts', PACKAGE = 'Rnmr1D', x, istart, iend, decal_max)
}

C_align_segment <- function(x, s, istart, iend) {
    .Call('Rnmr1D_C_align_segment', PACKAGE = 'Rnmr1D', x, s, istart, iend)
}

C_noise_estimation <- function(x, n1, n2) {
    .Call('Rnmr1D_C_noise_estimation', PACKAGE = 'Rnmr1D', x, n1, n2)
}

C_aibin_buckets <- function(x, b, v, l, n1, n2) {
    .Call('Rnmr1D_C_aibin_buckets', PACKAGE = 'Rnmr1D', x, b, v, l, n1, n2)
}

C_buckets_integrate <- function(x, b, mode) {
    .Call('Rnmr1D_C_buckets_integrate', PACKAGE = 'Rnmr1D', x, b, mode)
}

C_all_buckets_integrate <- function(x, b, mode) {
    .Call('Rnmr1D_C_all_buckets_integrate', PACKAGE = 'Rnmr1D', x, b, mode)
}

C_buckets_CSN_normalize <- function(b) {
    .Call('Rnmr1D_C_buckets_CSN_normalize', PACKAGE = 'Rnmr1D', b)
}

